/**
 * @file aboutdialog.cpp
 * @brief Implementation of the AboutDialog class.
 *
 * Constructs a fixed-size dialog with application branding, version info,
 * a short description, technology stack, and the developer's name.
 */

#include "aboutdialog.h"

#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QApplication>
#include <QPixmap>

/**
 * Build the About dialog layout with centered labels for:
 *  - Application name (large bold font)
 *  - Version number (from version.h, generated by CMake)
 *  - Description of the application's purpose
 *  - Technology stack
 *  - Author attribution
 */
AboutDialog::AboutDialog(QWidget *parent) : QDialog(parent)
{
    setWindowTitle("About CANBridge");
    setFixedSize(400, 300);

    QVBoxLayout* mainLayout = new QVBoxLayout(this);

    // Application logo
    QLabel* titleLabel = new QLabel();
    QPixmap logo(":/logo.png");
    titleLabel->setPixmap(logo.scaledToHeight(90, Qt::SmoothTransformation));
    titleLabel->setAlignment(Qt::AlignCenter);
    mainLayout->addWidget(titleLabel);

    // Version (injected at build time via CMake configure_file)
    QLabel* versionLabel = new QLabel(QString("Version: %1").arg(APP_VERSION));
    versionLabel->setAlignment(Qt::AlignCenter);
    mainLayout->addWidget(versionLabel);

    mainLayout->addSpacing(20);

    // Application description
    QLabel* descLabel = new QLabel(
        "Bridge CAN bus communication across network (TCP/IP). "
        "Send and receive frames through TCP."
        );
    descLabel->setWordWrap(true);
    descLabel->setAlignment(Qt::AlignCenter);
    mainLayout->addWidget(descLabel);

    mainLayout->addSpacing(20);

    // Technology stack
    QLabel* techLabel = new QLabel("Built with Qt 6 C++");
    techLabel->setAlignment(Qt::AlignCenter);
    QFont techFont;
    techFont.setItalic(true);
    techLabel->setFont(techFont);
    mainLayout->addWidget(techLabel);

    mainLayout->addSpacing(20);

    // Author credit
    QLabel* authorLabel = new QLabel("Developed by Er. Ismail KARROUD");
    authorLabel->setAlignment(Qt::AlignCenter);
    QFont authorFont;
    authorFont.setBold(true);
    authorLabel->setFont(authorFont);
    mainLayout->addWidget(authorLabel);

    mainLayout->addStretch();
}
